apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: chainguard.dev
  namespace: cert-manager
spec:
  sources:
  - useDefaultCAs: true
  - configMap:
      name: cgr-ca
      key: ca.crt
  target:
    configMap:
      key: "bundle.pem"
