---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    repoURL: https://charts.jetstack.io
    targetRevision: v1.17.0 
    helm:
      releaseName: cert-manager
      values: |
        crds:
          enabled: true
  destination:
    name: "in-cluster"
    namespace: 'cert-manager'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true